# Generated by Django 5.2.13 on 2026-04-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fragrance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tagline", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "collection",
                    models.CharField(
                        choices=[
                            ("core", "Core Signature"),
                            ("niche", "Ultra Niche"),
                            ("elemental", "Elemental"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "concentration",
                    models.CharField(
                        choices=[
                            ("extrait", "Extrait de Parfum"),
                            ("edp", "Eau de Parfum"),
                            ("edt", "Eau de Toilette"),
                        ],
                        max_length=10,
                    ),
                ),
                ("note_1", models.CharField(blank=True, max_length=50)),
                ("note_2", models.CharField(blank=True, max_length=50)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-joined_at"],
            },
        ),
    ]
