# Generated by Django 5.2.13 on 2026-04-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FounderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        default="Founder & Creative Director", max_length=100
                    ),
                ),
                ("bio_1", models.TextField(help_text="First paragraph")),
                (
                    "bio_2",
                    models.TextField(
                        blank=True, help_text="Second paragraph (optional)"
                    ),
                ),
                ("photo", models.ImageField(upload_to="founder/")),
            ],
            options={
                "verbose_name": "Founder Profile",
                "verbose_name_plural": "Founder Profile",
            },
        ),
        migrations.AddField(
            model_name="fragrance",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="fragrances/"),
        ),
    ]
